import { StyleSheet } from "react-native";

import { FONTS, PALETTE } from "../../../../theme/palette";

export const screenStyles = StyleSheet.create({
  recordRow: {
    backgroundColor: PALETTE.surfaceContainerLowest,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  participantsScrollContent: {
    paddingHorizontal: 22,
  },
  reviewScrollContent: {
    paddingHorizontal: 24,
  },
  stickyFlowHeader: {
    backgroundColor: PALETTE.surface,
    paddingHorizontal: 22,
    paddingBottom: 18,
    zIndex: 5,
  },
  stickyReviewHeaderWrap: {
    backgroundColor: PALETTE.surface,
    paddingBottom: 0,
    zIndex: 5,
  },
  reviewListViewport: {
    overflow: "hidden",
  },
  reviewListContent: {
    paddingTop: 20,
  },
  stickyHomeHeader: {
    backgroundColor: PALETTE.surface,
    paddingHorizontal: 20,
    paddingBottom: 18,
    zIndex: 5,
  },
  frequentFriendsRow: {
    gap: 18,
    paddingRight: 8,
  },
  frequentFriendItem: {
    alignItems: "center",
    gap: 8,
  },
  frequentFriendFrame: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  frequentFriendFrameSelected: {
    borderWidth: 2,
    borderColor: PALETTE.primaryContainer,
  },
  frequentFriendAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  participantInputShell: {
    minHeight: 60,
    backgroundColor: PALETTE.surfaceContainerLow,
    borderRadius: 999,
    paddingLeft: 18,
    paddingRight: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  participantInput: {
    flex: 1,
    minHeight: 52,
    color: PALETTE.onSurface,
    fontFamily: FONTS.body,
    fontSize: 18,
  },
  participantAddButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: PALETTE.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  participantPill: {
    minHeight: 78,
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: PALETTE.surfaceContainerLowest,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  payerOptionRow: {
    minHeight: 78,
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: PALETTE.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: "rgba(220,193,180,0.2)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  payerOptionRowSelected: {
    borderColor: PALETTE.primary,
    borderWidth: 2,
  },
  payerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  payerSelectedIndicator: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: PALETTE.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  payerUnselectedIndicator: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "rgba(157,68,1,0.28)",
    backgroundColor: PALETTE.surfaceContainerLowest,
  },
  participantAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  participantRemoveButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  participantEmptyCard: {
    borderRadius: 28,
    backgroundColor: PALETTE.surfaceContainerLowest,
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  errorPanel: {
    borderRadius: 28,
    backgroundColor: "#fff0ef",
    borderWidth: 1,
    borderColor: "#f4c5c0",
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 10,
  },
  itemsImportCard: {
    borderRadius: 28,
    backgroundColor: PALETTE.surfaceContainerLowest,
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  itemsImportIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(249,137,72,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  itemsImportPrimaryButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 999,
    backgroundColor: PALETTE.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  itemsImportSecondaryButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 999,
    backgroundColor: "#baf1e8",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  itemsImportButtonDisabled: {
    opacity: 0.68,
  },
  soonChip: {
    minHeight: 22,
    paddingHorizontal: 8,
    borderRadius: 999,
    backgroundColor: "rgba(249,137,72,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  itemsSectionSeparator: {
    height: 1,
    backgroundColor: "rgba(220,193,180,0.32)",
    marginTop: 4,
  },
  reviewStickySeparator: {
    height: 1,
    backgroundColor: "rgba(220,193,180,0.32)",
  },
  itemsListCard: {
    borderRadius: 24,
    backgroundColor: PALETTE.surfaceContainerLowest,
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  itemsManualAddButton: {
    minHeight: 70,
    borderRadius: 999,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "rgba(188, 110, 49, 0.28)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.5)",
  },
  itemsManualAddIconWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PALETTE.primary,
  },
  itemsNextButton: {
    minHeight: 62,
    borderRadius: 999,
    backgroundColor: PALETTE.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  itemDeleteButton: {
    minHeight: 54,
    width: 54,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "rgba(186,26,26,0.24)",
    backgroundColor: "#fff4f3",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  itemSaveButton: {
    flex: 1,
  },
  itemSaveButtonFull: {
    width: "100%",
  },
  assignHeaderSpacer: {
    width: 22,
    height: 22,
  },
  assignInputShell: {
    minHeight: 78,
    borderRadius: 20,
    backgroundColor: PALETTE.surfaceContainerLow,
    paddingHorizontal: 18,
    justifyContent: "center",
  },
  assignInputShellError: {
    borderWidth: 1.5,
    borderColor: "#cf3f38",
  },
  assignInput: {
    minHeight: 54,
    color: PALETTE.onSurface,
    fontFamily: FONTS.bodyMedium,
    fontSize: 18,
  },
  assignPriceInput: {
    minHeight: 54,
    color: PALETTE.onSurface,
    fontFamily: FONTS.headlineBlack,
    fontSize: 20,
  },
  categoryChip: {
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: PALETTE.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryChipActive: {
    backgroundColor: PALETTE.primary,
  },
  participantsContinueButton: {
    minHeight: 60,
    borderRadius: 999,
    backgroundColor: "#ff8a43",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  participantsContinueButtonDisabled: {
    backgroundColor: "#d8d4d1",
    shadowOpacity: 0,
    elevation: 0,
  },
  splitCategoryPill: {
    minHeight: 28,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "rgba(249,137,72,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  splitModeShell: {
    borderRadius: 999,
    backgroundColor: PALETTE.surfaceContainerLow,
    padding: 6,
  },
  splitParticipantCard: {
    borderRadius: 24,
    backgroundColor: PALETTE.surfaceContainerLowest,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  splitAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  splitStepperButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "rgba(188, 110, 49, 0.2)",
    backgroundColor: PALETTE.surfaceContainerLowest,
    alignItems: "center",
    justifyContent: "center",
  },
  splitStepperButtonActive: {
    backgroundColor: PALETTE.primary,
    borderColor: PALETTE.primary,
  },
  splitStepperValue: {
    minWidth: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  percentValueShell: {
    minWidth: 82,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 2,
  },
  percentValueInput: {
    minWidth: 46,
    paddingVertical: 0,
    color: PALETTE.primary,
    fontFamily: FONTS.headlineBold,
    fontSize: 28,
    textAlign: "right",
  },
  percentRemainderIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(189,114,47,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  splitSummaryCard: {
    borderRadius: 24,
    backgroundColor: PALETTE.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: "rgba(220,193,180,0.22)",
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 12,
  },
  splitHeaderSegmentedControl: {
    minHeight: 42,
    borderRadius: 999,
    backgroundColor: PALETTE.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: "rgba(220,193,180,0.7)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  splitHeaderSegment: {
    minWidth: 68,
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  splitHeaderSegmentLeft: {
    borderTopLeftRadius: 999,
    borderBottomLeftRadius: 999,
  },
  splitHeaderSegmentRight: {
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
  },
  splitHeaderSegmentDivider: {
    width: 1,
    height: 18,
    backgroundColor: "rgba(167,118,84,0.3)",
  },
  splitNoticeOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    zIndex: 20,
  },
  splitNoticeBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(57, 36, 18, 0.22)",
  },
  splitNoticeCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 28,
    backgroundColor: PALETTE.surfaceContainerLowest,
    paddingHorizontal: 22,
    paddingVertical: 22,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 8,
  },
  actionSheetCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 28,
    backgroundColor: PALETTE.surfaceContainerLowest,
    paddingHorizontal: 22,
    paddingVertical: 22,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 8,
  },
  splitNoticeButton: {
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: PALETTE.primary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  actionSheetButton: {
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: PALETTE.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  actionSheetButtonDanger: {
    backgroundColor: "rgba(207,63,56,0.12)",
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#e4e0dc",
    overflow: "hidden",
    marginTop: 18,
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: PALETTE.primary,
  },
  reviewProgressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#e4e0dc",
    overflow: "hidden",
    marginTop: 16,
  },
  reviewProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: PALETTE.primary,
  },
  reviewItemCardPending: {
    borderWidth: 1,
    borderColor: "rgba(249,137,72,0.35)",
  },
  reviewAssignButton: {
    minWidth: 92,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#ff8a43",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  resultsHeroCard: {
    borderRadius: 28,
    backgroundColor: PALETTE.primary,
    paddingHorizontal: 20,
    paddingVertical: 20,
    overflow: "hidden",
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  resultsHeroGlow: {
    position: "absolute",
    top: -20,
    right: -14,
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  resultsHeroChipMuted: {
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 12,
    backgroundColor: "rgba(58,35,12,0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  resultsHeroChip: {
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 12,
    backgroundColor: PALETTE.surfaceContainerLowest,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  resultsProgressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.2)",
    marginTop: 16,
    overflow: "hidden",
  },
  resultsProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: PALETTE.surfaceContainerLowest,
  },
  resultsPaidCard: {
    borderRadius: 24,
    backgroundColor: PALETTE.surfaceContainerLowest,
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  resultsBreakdownCard: {
    borderRadius: 24,
    backgroundColor: PALETTE.surfaceContainerLowest,
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  resultsBreakdownCardSettled: {
    opacity: 0.92,
  },
  resultsAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    overflow: "hidden",
  },
  resultsCheckBubble: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: PALETTE.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  resultsCheckBubbleSettled: {
    backgroundColor: PALETTE.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  resultsPrimaryButton: {
    minHeight: 58,
    borderRadius: 999,
    backgroundColor: PALETTE.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  resultsSecondaryButton: {
    minHeight: 58,
    borderRadius: 999,
    backgroundColor: "#baf1e8",
    alignItems: "center",
    justifyContent: "center",
  },
  selectRow: {
    backgroundColor: PALETTE.surfaceContainerLow,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  selectRowActive: {
    backgroundColor: "rgba(249,137,72,0.18)",
  },
  modePillShell: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  modePillButton: {
    minHeight: 40,
    borderRadius: 999,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PALETTE.surfaceContainerLow,
  },
  modePillButtonActive: {
    backgroundColor: "#f8eadf",
    borderWidth: 1,
    borderColor: "rgba(191,95,0,0.16)",
  },
  togglePill: {
    flex: 1,
    minHeight: 40,
    borderRadius: 999,
    paddingHorizontal: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  flex: {
    flex: 1,
  },
  homeScrollContent: {
    paddingHorizontal: 20,
    gap: 28,
  },
  mainTabScrollContent: {
    paddingHorizontal: 20,
  },
  mainTabHeaderWrap: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
    backgroundColor: PALETTE.surface,
    zIndex: 5,
  },
  homeHeader: {
    minHeight: 48,
    justifyContent: "center",
  },
  ctaHalo: {
    backgroundColor: "rgba(0,106,96,0.06)",
    borderRadius: 34,
    padding: 8,
  },
  homeCta: {
    minHeight: 178,
    borderRadius: 30,
    backgroundColor: "#bd722f",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    overflow: "hidden",
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  homeCtaIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: PALETTE.surfaceContainerLowest,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  recentRow: {
    paddingVertical: 0,
  },
  recentShadowWrap: {
    paddingBottom: 6,
    marginBottom: -6,
    overflow: "visible",
  },
  settingsInlineAction: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(249,137,72,0.12)",
  },
  settingsInlineActionActive: {
    backgroundColor: "rgba(249,137,72,0.2)",
  },
  recentSwipeDeleteAction: {
    minWidth: 92,
    marginLeft: 12,
    borderRadius: 24,
    backgroundColor: "#cf3f38",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 14,
  },
  undoBanner: {
    backgroundColor: "#cf3f38",
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  undoButton: {
    minWidth: 72,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.4)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  unpaidDotMuted: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#dcd8d6",
    borderWidth: 2,
    borderColor: PALETTE.surface,
  },
  unpaidDotSoft: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#ece7e2",
    borderWidth: 2,
    borderColor: PALETTE.surface,
  },
  homeTabShell: {
    backgroundColor: PALETTE.surfaceContainerLowest,
    borderRadius: 36,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(220,193,180,0.28)",
    shadowColor: PALETTE.primary,
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    overflow: "hidden",
  },
  homeTabButton: {
    flex: 1,
    minHeight: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  homeTabButtonActive: {
    backgroundColor: "rgba(249,137,72,0.12)",
  },
  homeBalanceCardWrap: {
    flex: 1,
  },
  homeBalanceCardContent: {
    minHeight: 74,
    justifyContent: "flex-start",
    gap: 18,
  },
  settingsAvatarWrap: {
    width: 84,
    height: 84,
    borderRadius: 42,
    marginTop: 24,
    backgroundColor: "rgba(249,137,72,0.16)",
    borderWidth: 1,
    borderColor: "rgba(249,137,72,0.2)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  settingsAvatarImage: {
    width: "100%",
    height: "100%",
  },
  settingsFeatureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  settingsFeatureToggle: {
    minWidth: 70,
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(189,114,47,0.24)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PALETTE.surface,
  },
  settingsFeatureToggleActive: {
    backgroundColor: PALETTE.primary,
    borderColor: PALETTE.primary,
  },
});
