import { FONTS, PALETTE } from "../../../../../theme/palette";
import { StyleSheet } from "react-native";

export const commonStyles = {
  participantPill: {
      minHeight: 78,
      borderRadius: 28,
      paddingHorizontal: 16,
      paddingVertical: 14,
      backgroundColor: PALETTE.surfaceContainerLowest,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.05,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
  participantAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
  participantRemoveButton: {
      width: 34,
      height: 34,
      alignItems: "center",
      justifyContent: "center",
    },
  errorPanel: {
      borderRadius: 28,
      backgroundColor: PALETTE.dangerSurface,
      borderWidth: 1,
      borderColor: PALETTE.dangerBorder,
      paddingHorizontal: 18,
      paddingVertical: 18,
      gap: 10,
    },
  itemsNextButton: {
      minHeight: 62,
      borderRadius: 999,
      backgroundColor: PALETTE.primary,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.12,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 5,
    },
  participantsContinueButton: {
      minHeight: 60,
      borderRadius: 999,
      backgroundColor: PALETTE.primary,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.14,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 5,
    },
  participantsContinueButtonDisabled: {
      backgroundColor: PALETTE.surfaceContainerHighest,
      shadowOpacity: 0,
      elevation: 0,
    },
  flowContinueButtonContent: {
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 22,
    },
  flowContinueButtonLabel: {
      flex: 1,
      textAlign: "center",
    },
  flowContinueButtonIconSlot: {
      width: 20,
      alignItems: "flex-end",
      justifyContent: "center",
    },
  actionSheetCard: {
      width: "100%",
      maxWidth: 360,
      borderRadius: 28,
      backgroundColor: PALETTE.surfaceContainerLowest,
      paddingHorizontal: 22,
      paddingVertical: 22,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.16,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: 14 },
      elevation: 8,
    },
  actionSheetOptionsScroll: {
      maxHeight: 320,
    },
  actionSheetOptionsContent: {
      gap: 10,
      paddingRight: 2,
    },
  splitNoticeButtonCompact: {
      flex: 1,
      marginTop: 0,
    },
  splitNoticeButtonSecondary: {
      backgroundColor: PALETTE.secondaryContainer,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
    },
  reminderActionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginTop: 4,
    },
  reminderRemoveButton: {
      minHeight: 48,
      width: 48,
      borderRadius: 999,
      borderWidth: 1.5,
      borderColor: "rgba(186,26,26,0.24)",
      backgroundColor: PALETTE.dangerSurface,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
  actionSheetButton: {
      minHeight: 48,
      borderRadius: 18,
      backgroundColor: PALETTE.surfaceContainerLow,
      justifyContent: "center",
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
  actionSheetButtonSelected: {
      backgroundColor: PALETTE.brandOverlayStrong,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
    },
  actionSheetButtonDanger: {
      backgroundColor: PALETTE.dangerSurface,
    },
  actionIconGridRow: {
      width: "100%",
      flexDirection: "row",
      gap: 10,
    },
  actionIconGridButton: {
      flex: 1,
      minHeight: 104,
      borderRadius: 20,
      backgroundColor: PALETTE.surfaceContainerLow,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 8,
      paddingVertical: 12,
      gap: 7,
    },
  actionIconGridButtonDanger: {
      backgroundColor: PALETTE.dangerSurface,
      borderWidth: 1,
      borderColor: "rgba(186,26,26,0.22)",
    },
  actionIconGridBadge: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: PALETTE.brandOverlayStrong,
      alignItems: "center",
      justifyContent: "center",
    },
  actionIconGridBadgeDanger: {
      backgroundColor: "rgba(186,26,26,0.14)",
    },
  actionIconGridLabelWrap: {
      minHeight: 20,
      justifyContent: "center",
      alignItems: "center",
    },
  toastOverlay: {
      position: "absolute",
      left: 24,
      right: 24,
      alignItems: "center",
      zIndex: 30,
    },
  toastCard: {
      minHeight: 40,
      borderRadius: 999,
      backgroundColor: "rgba(63, 46, 32, 0.95)",
      paddingHorizontal: 16,
      paddingVertical: 10,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000000",
      shadowOpacity: 0.16,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 6,
    },
  avatarImage: {
      overflow: "hidden",
    },
  modePillShell: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
    },
  modePillButton: {
      minHeight: 40,
      borderRadius: 999,
      paddingHorizontal: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: PALETTE.surfaceContainerLow,
    },
  modePillButtonActive: {
      backgroundColor: PALETTE.secondaryContainer,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
    },
  recentRow: {
      paddingVertical: 0,
    },
  homeTabShell: {
      backgroundColor: PALETTE.surfaceContainerLowest,
      borderRadius: 36,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.08,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
      elevation: 4,
      overflow: "hidden",
    },
  homeTabButton: {
      flex: 1,
      minHeight: 60,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 22,
    },
  homeTabButtonActive: {
      backgroundColor: PALETTE.brandOverlay,
    },
  itemsSectionSeparator: {
      height: 1,
      backgroundColor: PALETTE.divider,
      marginTop: 4,
    },
  itemsListCard: {
      borderRadius: 24,
      backgroundColor: PALETTE.surfaceContainerLowest,
      paddingHorizontal: 18,
      paddingVertical: 18,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.05,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
  assignInputShell: {
      minHeight: 78,
      borderRadius: 20,
      backgroundColor: PALETTE.surfaceContainerLow,
      paddingHorizontal: 18,
      justifyContent: "center",
    },
  assignInput: {
      minHeight: 54,
      color: PALETTE.onSurface,
      fontFamily: FONTS.bodyMedium,
      fontSize: 18,
    },
  splitNoticeOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 24,
      zIndex: 20,
    },
  splitNoticeBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(57, 36, 18, 0.22)",
    },
  splitNoticeCard: {
      width: "100%",
      maxWidth: 360,
      borderRadius: 28,
      backgroundColor: PALETTE.surfaceContainerLowest,
      paddingHorizontal: 22,
      paddingVertical: 22,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.16,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: 14 },
      elevation: 8,
    },
  splitNoticeButton: {
      minHeight: 48,
      borderRadius: 999,
      backgroundColor: PALETTE.primary,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 4,
    },
  confirmChoiceSecondaryButton: {
      minHeight: 48,
      borderRadius: 18,
      backgroundColor: PALETTE.surfaceContainerLow,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
  selectRow: {
      minHeight: 78,
      backgroundColor: PALETTE.surfaceContainerLow,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 12,
      justifyContent: "center",
    },
  togglePill: {
      flex: 1,
      minHeight: 40,
      borderRadius: 999,
      paddingHorizontal: 14,
      justifyContent: "center",
      alignItems: "center",
    },
  flex: {
      flex: 1,
    },
  recentShadowWrap: {
      paddingHorizontal: 6,
      marginHorizontal: -6,
      paddingBottom: 6,
      marginBottom: -6,
      overflow: "visible",
    },
  settingsInlineAction: {
      width: 40,
      height: 40,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: PALETTE.brandOverlay,
    },
  undoBanner: {
      backgroundColor: PALETTE.danger,
      borderRadius: 24,
      paddingHorizontal: 18,
      paddingVertical: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
  undoButton: {
      minWidth: 72,
      height: 36,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.4)",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 14,
    },
  recordRow: {
      backgroundColor: PALETTE.surfaceContainerLowest,
      borderRadius: 24,
      paddingHorizontal: 18,
      paddingVertical: 18,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.06,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
  stickyReviewHeaderWrap: {
      backgroundColor: PALETTE.surface,
      paddingBottom: 0,
      zIndex: 5,
    },
  participantEmptyCard: {
      borderRadius: 28,
      backgroundColor: PALETTE.surfaceContainerLowest,
      paddingHorizontal: 18,
      paddingVertical: 18,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.04,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 2,
    },
  soonChip: {
      minHeight: 22,
      paddingHorizontal: 8,
      borderRadius: 999,
      backgroundColor: PALETTE.brandOverlayStrong,
      alignItems: "center",
      justifyContent: "center",
    },
  assignHeaderSpacer: {
      width: 22,
      height: 22,
    },
  splitSummaryCard: {
      borderRadius: 24,
      backgroundColor: PALETTE.surfaceContainerLowest,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
      paddingHorizontal: 18,
      paddingVertical: 16,
      gap: 12,
    },
  progressTrack: {
      height: 8,
      borderRadius: 999,
      backgroundColor: PALETTE.track,
      overflow: "hidden",
      marginTop: 18,
    },
  progressFill: {
      height: "100%",
      borderRadius: 999,
      backgroundColor: PALETTE.primary,
    },
  resultsHeroChipMuted: {
      minHeight: 28,
      borderRadius: 999,
      paddingHorizontal: 12,
      backgroundColor: "rgba(86, 45, 20, 0.28)",
      alignItems: "center",
      justifyContent: "center",
    },
  resultsSecondaryButton: {
      flex: 1,
      minHeight: 58,
      borderRadius: 999,
      backgroundColor: PALETTE.secondaryContainer,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
    },
  selectRowActive: {
      backgroundColor: PALETTE.brandOverlayStrong,
    },
  recentSwipeDeleteAction: {
      minWidth: 92,
      marginLeft: 12,
      borderRadius: 24,
      backgroundColor: PALETTE.danger,
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingHorizontal: 14,
    },
  unpaidDotMuted: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: PALETTE.surfaceContainerHighest,
      borderWidth: 2,
      borderColor: PALETTE.surface,
    },
  unpaidDotSoft: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: PALETTE.surfaceContainerHigh,
      borderWidth: 2,
      borderColor: PALETTE.surface,
    },
} as const;

