import { FONTS, PALETTE } from "../../../../../theme/palette";
import { StyleSheet } from "react-native";

export const flowStyles = {
  participantsScrollContent: {
      paddingHorizontal: 22,
    },
  reviewScrollContent: {
      paddingHorizontal: 24,
    },
  stickyFlowHeader: {
      backgroundColor: PALETTE.surface,
      paddingHorizontal: 22,
      paddingBottom: 18,
      zIndex: 5,
    },
  reviewListViewport: {
      overflow: "visible",
    },
  splitScrollViewport: {
      flex: 1,
      overflow: "hidden",
    },
  reviewListContent: {
      paddingTop: 20,
    },
  swipeableVisibleContainer: {
      overflow: "visible",
    },
  frequentFriendsRow: {
      gap: 18,
      paddingRight: 8,
    },
  frequentFriendItem: {
      alignItems: "center",
      gap: 8,
    },
  frequentFriendFrame: {
      width: 60,
      height: 60,
      borderRadius: 30,
      alignItems: "center",
      justifyContent: "center",
    },
  frequentFriendFrameSelected: {
      borderWidth: 2,
      borderColor: PALETTE.primaryContainer,
    },
  frequentFriendAvatar: {
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: "center",
      justifyContent: "center",
    },
  participantInputShell: {
      minHeight: 78,
      backgroundColor: PALETTE.surfaceContainerLow,
      borderRadius: 20,
      paddingLeft: 18,
      paddingRight: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
  participantInput: {
      flex: 1,
      minHeight: 54,
      color: PALETTE.onSurface,
      fontFamily: FONTS.bodyMedium,
      fontSize: 18,
    },
  participantAddButton: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: PALETTE.primary,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.12,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 4,
    },
  payerOptionRow: {
      minHeight: 78,
      borderRadius: 28,
      paddingHorizontal: 16,
      paddingVertical: 14,
      backgroundColor: PALETTE.surfaceContainerLowest,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 14,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.05,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
  payerOptionRowSelected: {
      borderColor: PALETTE.primary,
      borderWidth: 2,
    },
  payerAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
  payerSelectedIndicator: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: PALETTE.primary,
      alignItems: "center",
      justifyContent: "center",
    },
  payerUnselectedIndicator: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: PALETTE.outline,
      backgroundColor: PALETTE.surfaceContainerLowest,
    },
  itemsImportCard: {
      borderRadius: 28,
      backgroundColor: PALETTE.surfaceContainerLowest,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.04,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 2,
    },
  reviewProgressCard: {
      paddingHorizontal: 18,
      paddingVertical: 18,
    },
  itemsImportCardButton: {
      minHeight: 72,
      paddingHorizontal: 18,
      paddingVertical: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
  itemsImportIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: PALETTE.brandOverlayStrong,
      alignItems: "center",
      justifyContent: "center",
    },
  reviewStickySeparator: {
      height: 1,
      backgroundColor: PALETTE.divider,
    },
  itemsManualAddButton: {
      minHeight: 70,
      borderRadius: 999,
      borderWidth: 1.5,
      borderStyle: "dashed",
      borderColor: PALETTE.outline,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(255,255,255,0.5)",
    },
  itemsManualAddIconWrap: {
      width: 22,
      height: 22,
      borderRadius: 11,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: PALETTE.primary,
    },
  itemDeleteButton: {
      minHeight: 54,
      width: 54,
      borderRadius: 999,
      borderWidth: 1.5,
      borderColor: "rgba(186,26,26,0.24)",
      backgroundColor: PALETTE.dangerSurface,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
  itemSaveButton: {
      flex: 1,
    },
  itemSaveButtonFull: {
      width: "100%",
    },
  assignPriceInput: {
      minHeight: 54,
      color: PALETTE.onSurface,
      fontFamily: FONTS.headlineBlack,
      fontSize: 20,
    },
  categoryChip: {
      minHeight: 34,
      paddingHorizontal: 14,
      borderRadius: 999,
      backgroundColor: PALETTE.surfaceContainerLow,
      alignItems: "center",
      justifyContent: "center",
    },
  categoryChipActive: {
      backgroundColor: PALETTE.primary,
    },
  splitCategoryPill: {
      minHeight: 28,
      paddingHorizontal: 14,
      borderRadius: 999,
      backgroundColor: PALETTE.brandOverlay,
      alignItems: "center",
      justifyContent: "center",
    },
  splitCompactHeaderOverlay: {
      position: "absolute",
      left: 0,
      right: 0,
      zIndex: 6,
      elevation: 6,
      paddingHorizontal: 22,
      backgroundColor: PALETTE.surface,
    },
  splitCompactHeaderCard: {
      borderBottomWidth: 1,
      borderBottomColor: PALETTE.divider,
      paddingTop: 8,
      paddingBottom: 10,
      gap: 2,
    },
  splitCompactHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
  splitModeShell: {
      borderRadius: 999,
      backgroundColor: PALETTE.surfaceContainerLow,
      padding: 6,
    },
  splitParticipantCard: {
      borderRadius: 24,
      backgroundColor: PALETTE.surfaceContainerLowest,
      paddingHorizontal: 16,
      paddingVertical: 16,
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffset: { width: 0, height: 0 },
      elevation: 0,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
      position: "relative",
      overflow: "hidden",
    },
  splitParticipantOverlayPressable: {
      ...StyleSheet.absoluteFillObject,
    },
  splitAvatar: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: "center",
      justifyContent: "center",
    },
  splitStepperButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
      backgroundColor: PALETTE.surfaceContainerLowest,
      alignItems: "center",
      justifyContent: "center",
    },
  splitStepperButtonActive: {
      backgroundColor: PALETTE.primary,
      borderColor: PALETTE.primary,
    },
  splitStepperValue: {
      minWidth: 28,
      alignItems: "center",
      justifyContent: "center",
    },
  percentValueShell: {
      minWidth: 82,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 2,
    },
  percentValueInput: {
      minWidth: 46,
      paddingVertical: 0,
      color: PALETTE.primary,
      fontFamily: FONTS.headlineBold,
      fontSize: 28,
      textAlign: "right",
    },
  percentRemainderIcon: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: PALETTE.brandOverlay,
      alignItems: "center",
      justifyContent: "center",
    },
  splitHeaderSegmentedControl: {
      minHeight: 42,
      borderRadius: 999,
      backgroundColor: PALETTE.surfaceContainerLowest,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 6,
      paddingVertical: 4,
    },
  splitHeaderSegment: {
      minWidth: 68,
      minHeight: 32,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 12,
    },
  splitHeaderSegmentLeft: {
      borderTopLeftRadius: 999,
      borderBottomLeftRadius: 999,
    },
  splitHeaderSegmentRight: {
      borderTopRightRadius: 999,
      borderBottomRightRadius: 999,
    },
  splitHeaderSegmentDivider: {
      width: 1,
      height: 18,
      backgroundColor: PALETTE.outline,
    },
  reviewProgressTrack: {
      height: 8,
      borderRadius: 999,
      backgroundColor: PALETTE.track,
      overflow: "hidden",
      marginTop: 16,
    },
  reviewProgressFill: {
      height: "100%",
      borderRadius: 999,
      backgroundColor: PALETTE.primary,
    },
  reviewItemCardPending: {
      borderWidth: 1,
      borderColor: PALETTE.warningBorder,
    },
  reviewAssignButton: {
      minWidth: 92,
      height: 42,
      borderRadius: 21,
      backgroundColor: PALETTE.tertiary,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 14,
    },
  resultsHeroCard: {
      borderRadius: 28,
      backgroundColor: PALETTE.primary,
      paddingHorizontal: 20,
      paddingVertical: 20,
      overflow: "hidden",
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.1,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 5,
    },
  resultsHeroGlow: {
      position: "absolute",
      top: -20,
      right: -14,
      width: 92,
      height: 92,
      borderRadius: 46,
      backgroundColor: "rgba(255,255,255,0.08)",
    },
  resultsHeroChip: {
      minHeight: 28,
      borderRadius: 999,
      paddingHorizontal: 12,
      backgroundColor: PALETTE.surfaceContainerLowest,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 6,
    },
  resultsProgressTrack: {
      height: 8,
      borderRadius: 999,
      backgroundColor: "rgba(255,255,255,0.2)",
      marginTop: 16,
      overflow: "hidden",
    },
  resultsProgressFill: {
      height: "100%",
      borderRadius: 999,
      backgroundColor: PALETTE.surfaceContainerLowest,
    },
  resultsPaidCard: {
      borderRadius: 24,
      backgroundColor: PALETTE.surfaceContainerLowest,
      paddingHorizontal: 18,
      paddingVertical: 18,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.05,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
  resultsBreakdownCard: {
      borderRadius: 24,
      backgroundColor: PALETTE.surfaceContainerLowest,
      paddingHorizontal: 18,
      paddingVertical: 18,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.05,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
  resultsBreakdownCardSettled: {
      opacity: 0.92,
    },
  resultsAvatar: {
      width: 46,
      height: 46,
      borderRadius: 23,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
  resultsCheckBubble: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: PALETTE.primary,
      alignItems: "center",
      justifyContent: "center",
    },
  resultsCheckBubbleSettled: {
      backgroundColor: PALETTE.success,
      alignItems: "center",
      justifyContent: "center",
    },
  resultsPrimaryButton: {
      flex: 1,
      minHeight: 58,
      borderRadius: 999,
      backgroundColor: PALETTE.primary,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 14,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.12,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 5,
    },
  splitFooterInlineSummary: {
      gap: 4,
      marginTop: 4,
    },
  splitFooterContent: {
      position: "relative",
    },
  splitSkipCornerButton: {
      position: "absolute",
      top: -2,
      right: -2,
      minHeight: 30,
      borderRadius: 999,
      backgroundColor: PALETTE.secondaryContainer,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 10,
      zIndex: 2,
    },
  itemsFooterInlineSummary: {
      gap: 4,
      marginTop: 4,
    },
  itemsScrollCueSlot: {
      minHeight: 34,
      alignItems: "center",
      justifyContent: "center",
    },
  itemsScrollCueButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: "rgba(255,253,250,0.96)",
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 3,
    },
  itemsScrollCueButtonHidden: {
      opacity: 0,
    },
  resultsInvalidCard: {
      marginTop: 24,
      borderRadius: 28,
      backgroundColor: PALETTE.surfaceContainerLowest,
      paddingHorizontal: 20,
      paddingVertical: 20,
      gap: 12,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
      shadowColor: PALETTE.primary,
      shadowOpacity: 0.05,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
  resultsInvalidIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: PALETTE.brandOverlay,
      alignItems: "center",
      justifyContent: "center",
    },
  resultsInvalidPrimaryButton: {
      minHeight: 52,
      borderRadius: 999,
      backgroundColor: PALETTE.primary,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 16,
    },
  resultsInvalidSecondaryButton: {
      minHeight: 52,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: PALETTE.outlineVariant,
      backgroundColor: PALETTE.secondaryContainer,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 16,
    },
  reviewLastItemShadowSpacer: {
      marginBottom: 6,
    },
} as const;

